$0 --verbose \
	--temperature \
	--ac-voltage \
	--ac-current \
	--battery-voltage \
	--charge-current \
	--discharge-current \
	--ac-present \
	--reg-0x00-bit2 \
	--battery-charging \
	--battery-connected
