$0 --verbose \
	--temperature \
	--ac_voltage \
	--ac_current \
	--battery_voltage \
	--charge_current \
	--discharge_current \
	--ac_present \
	--reg_0x00_bit2 \
	--battery_charging \
	--battery_connected
